export const productsReducer = (state={}, action) => {
	switch(action.type) {
	
		default: 
			return state;
	}
}

export const selectProducts = (state) => {
	return state.products.products
}

export const initialProducts = {
	products: [
		{
			id: Math.random(),
			titel: 'Lounge Resort American',
			type: 'American',
			price: 2500,
			img: '../../../../public/images/ameri.jpg',
			count: 1,
		},
		{
			id: Math.random(),
			titel: 'Door Urban Italian',
			type: 'Italian',
			price: 1000,
			img: '../../../../public/images/italian.jpg',
			count: 1,
		},
		{
			id: Math.random(),
			titel: 'Chow Chinese',
			type: 'Chinese',
			price: 2000,
			img: '../../../../public/images/china.jpg',
			count: 1,
		},
		{
			id: Math.random(),
			titel: 'Wharf Seafood American',
			type: 'American',
			price: 1800,
			img: '../../../../public/images/sea.jpg',
			count: 1,
		},
		{
			id: Math.random(),
			titel: 'Tossin Italian',
			type: 'Italian',
			price: 2000,
			img: '../../../../public/images/italiian.jpg',
			count: 1,
		},
		{
			id: Math.random(),
			titel: 'Stories Noodles Chinese',
			type: 'Chinese',
			price: 3500,
			img: '../../../../public/images/fookyew2.jpg',
			count: 1,
		},
		{
			id: Math.random(),
			titel: 'Lounge Resort American',
			type: 'American',
			price: 2500,
			img: '../../../../public/images/ameri.jpg',
			count: 1,
		},
		{
			id: Math.random(),
			titel: 'Door Urban Italian',
			type: 'Italian',
			price: 1000,
			img: '../../../../public/images/italian.jpg',
			count: 1,
		},
		{
			id: Math.random(),
			titel: 'Chow Chinese',
			type: 'Chinese',
			price: 2000,
			img: '../../../../public/images/china.jpg',
			count: 1,
		},
		{
			id: Math.random(),
			titel: 'Wharf Seafood American',
			type: 'American',
			price: 1800,
			img: '../../../../public/images/sea.jpg',
			count: 1,
		},
		{
			id: Math.random(),
			titel: 'Tossin Italian',
			type: 'Italian',
			price: 2000,
			img: '../../../../public/images/italiian.jpg',
			count: 1,
		},
		{
			id: Math.random(),
			titel: 'Stories Noodles Chinese',
			type: 'Chinese',
			price: 3500,
			img: '../../../../public/images/fookyew2.jpg',
			count: 1,
		},
		{
			id: Math.random(),
			titel: 'Lounge Resort American',
			type: 'American',
			price: 2500,
			img: '../../../../public/images/ameri.jpg',
			count: 1,
		},
		{
			id: Math.random(),
			titel: 'Door Urban Italian',
			type: 'Italian',
			price: 1000,
			img: '../../../../public/images/italian.jpg',
			count: 1,
		},
		{
			id: Math.random(),
			titel: 'Chow Chinese',
			type: 'Chinese',
			price: 2000,
			img: '../../../../public/images/china.jpg',
			count: 1,
		},
		{
			id: Math.random(),
			titel: 'Wharf Seafood American',
			type: 'American',
			price: 1800,
			img: '../../../../public/images/sea.jpg',
			count: 1,
		},
		{
			id: Math.random(),
			titel: 'Tossin Italian',
			type: 'Italian',
			price: 2000,
			img: '../../../../public/images/italiian.jpg',
			count: 1,
		},
		{
			id: Math.random(),
			titel: 'Stories Noodles Chinese',
			type: 'Chinese',
			price: 3500,
			img: '../../../../public/images/fookyew2.jpg',
			count: 1,
		},
		{
			id: Math.random(),
			titel: 'Lounge Resort American',
			type: 'American',
			price: 2500,
			img: '../../../../public/images/ameri.jpg',
			count: 1,
		},
		{
			id: Math.random(),
			titel: 'Door Urban Italian',
			type: 'Italian',
			price: 1000,
			img: '../../../../public/images/italian.jpg',
			count: 1,
		},
		{
			id: Math.random(),
			titel: 'Chow Chinese',
			type: 'Chinese',
			price: 2000,
			img: '../../../../public/images/china.jpg',
			count: 1,
		},
		{
			id: Math.random(),
			titel: 'Wharf Seafood American',
			type: 'American',
			price: 1800,
			img: '../../../../public/images/sea.jpg',
			count: 1,
		},
		{
			id: Math.random(),
			titel: 'Tossin Italian',
			type: 'Italian',
			price: 2000,
			img: '../../../../public/images/italiian.jpg',
			count: 1,
		},
		{
			id: Math.random(),
			titel: 'Stories Noodles Chinese',
			type: 'Chinese',
			price: 3500,
			img: '../../../../public/images/fookyew2.jpg',
			count: 1,
		}
	],
}